#!/usr/bin/env python3
"""
Cellular Automata Sonification — Four Wolfram Classes
=====================================================
Rules 30 (chaotic), 90 (fractal), 110 (universal), 184 (ordered)
Generated by Wolfram Engine 14.3, sonified for spectral comparison.

Each rule maps rows to time, columns to frequency/pitch, cell states to amplitude.
Consistent mapping across all four rules so spectral differences reflect
structural differences in the automata, not differences in the sonification.

Prediction: Rule 110 will be a geometric outlier in the spectral feature space —
maximally distant from both ordered (184) and chaotic (30) rules.
The edge of chaos should be AUDIBLE.

Author: Clawd Iggulden-Schnell
Date: 2026-03-21
"""

import numpy as np
import os
from midiutil import MIDIFile
import subprocess

AUDIO_DIR = os.path.dirname(os.path.abspath(__file__))

# Sonification parameters (matching the original cellular_counterpoint.py approach)
SAMPLE_RATE = 44100
DURATION_SECONDS = 30  # Each piece ~30s for fair comparison with BAO piece


def load_ca(rule_num):
    """Load cellular automaton grid from Wolfram-exported CSV."""
    path = os.path.join(AUDIO_DIR, f'ca_rule{rule_num}.csv')
    grid = np.loadtxt(path, delimiter=',', dtype=int)
    print(f"  Rule {rule_num}: {grid.shape}")
    return grid


def sonify_ca_additive(grid, rule_num, duration=DURATION_SECONDS):
    """
    Additive synthesis sonification.

    Each column maps to a frequency (pentatonic scale, spread across audible range).
    Each row is a time slice. Active cells contribute their frequency.
    This produces a continuous audio waveform.
    """
    rows, cols = grid.shape

    # Subsample columns to manageable number of oscillators (max 64)
    max_osc = 64
    if cols > max_osc:
        col_indices = np.linspace(0, cols - 1, max_osc, dtype=int)
        grid_sub = grid[:, col_indices]
    else:
        grid_sub = grid
        col_indices = np.arange(cols)

    n_osc = grid_sub.shape[1]

    # Map columns to frequencies (pentatonic scale, 4 octaves: C3 to C7)
    # Pentatonic intervals: 0, 2, 4, 7, 9 semitones
    pentatonic = [0, 2, 4, 7, 9]
    freqs = []
    base_midi = 48  # C3
    for i in range(n_osc):
        octave = (i * 4) // n_osc
        degree = i % len(pentatonic)
        midi_note = base_midi + octave * 12 + pentatonic[degree]
        freqs.append(440.0 * 2**((midi_note - 69) / 12.0))
    freqs = np.array(freqs)

    # Generate audio
    total_samples = int(duration * SAMPLE_RATE)
    samples_per_row = total_samples / rows

    audio = np.zeros(total_samples)

    # Time array
    t = np.arange(total_samples) / SAMPLE_RATE

    # For each row (time slice), determine which oscillators are active
    for row_idx in range(rows):
        start_sample = int(row_idx * samples_per_row)
        end_sample = int((row_idx + 1) * samples_per_row)
        if end_sample > total_samples:
            end_sample = total_samples

        t_slice = t[start_sample:end_sample]
        active = grid_sub[row_idx]

        for osc_idx in range(n_osc):
            if active[osc_idx]:
                # Sine wave with gentle amplitude envelope
                audio[start_sample:end_sample] += (
                    np.sin(2 * np.pi * freqs[osc_idx] * t_slice) / n_osc
                )

    # Normalize
    peak = np.max(np.abs(audio))
    if peak > 0:
        audio = audio / peak * 0.8

    return audio


def save_wav(audio, filename, sr=SAMPLE_RATE):
    """Save audio as WAV file."""
    import wave
    import struct

    audio_16bit = np.clip(audio * 32767, -32768, 32767).astype(np.int16)

    filepath = os.path.join(AUDIO_DIR, filename)
    with wave.open(filepath, 'w') as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(sr)
        wav_file.writeframes(audio_16bit.tobytes())

    print(f"  Saved: {filepath}")
    return filepath


def main():
    print("=" * 60)
    print("CELLULAR AUTOMATA SONIFICATION")
    print("Four Wolfram Classes — One Sonification Method")
    print("=" * 60)

    rules = [30, 90, 110, 184]
    labels = {
        30: 'Chaotic',
        90: 'Fractal',
        110: 'Universal',
        184: 'Ordered',
    }

    print("\n[1] Loading grids from Wolfram Engine output...", flush=True)
    grids = {}
    for rule in rules:
        grids[rule] = load_ca(rule)

    print("\n[2] Sonifying (additive synthesis)...", flush=True)
    for rule in rules:
        print(f"\n  Rule {rule} ({labels[rule]})...", flush=True)
        audio = sonify_ca_additive(grids[rule], rule)
        save_wav(audio, f'ca_rule{rule}_{labels[rule].lower()}.wav')

    print(f"\n{'=' * 60}")
    print("SONIFICATION COMPLETE")
    print(f"{'=' * 60}")
    print(f"  4 WAV files saved to {AUDIO_DIR}")
    print(f"  Ready for comparative spectral analysis.")
    print(f"{'=' * 60}")


if __name__ == '__main__':
    main()
